### ISSUE TITLE
Axios.create is undefined

### ISSUE THREAD

**Issue by Coreeze** [seatsio/seatsio-js#201]
Hi guys, I am playing around with your library - awesome product. Congrats!

I have an issue when I want to book the tickets, after selection: the following code returns the error `Axios.create is undefined at new SeatsioClient (SeatsioClient.js:16:1)`

This is the code I am running:
```
let client = await new SeatsioClient(
    Region.EU(),
    "workspace secret key"
  );
  await client.events.book("event key", ["1-1"]);
```

Any idea why this happens? I have been fighting with this for the last 2 days.

**Comment by Coreeze** [comment]
Thanks for the fast reply!

Just checked and had 1.3.4. Updated to 1.4.0 but the same problem is still there

**Comment by mroloux** [comment]
Hmm, not sure what's happening there. Is it possible to reproduce the issue on a public page, or in jsfiddle?

**Comment by Coreeze** [comment]
I got it to work - I was not calling the method the wrong way.

Thanks for the quick replies!
