### ISSUE TITLE
Property 'name' does not exist on type 'Event'.

### ISSUE THREAD

**Issue by KarimGabr** [seatsio/seatsio-js#215]
It seems like `name` is missing from `Event`, even though it is included in your API docs.

By the way this bug occurs only when using seatsIOClient `seatsIOClient.events.listAll()`, the name exists in the response object but is not included to the event instance.

Response Object: 
`{
    "id": 2493803,
    "key": "9feb7ccc-07ba-4bde-b4c0-e045706165e5",
    "name": "My Event 1",
    "chartKey": "2211787c-7d02-614f-6399-1ed6e5afb4a3",
    "bookWholeTables": false,
    "tableBookingConfig": {
        "mode": "INHERIT"
    },
    "createdOn": "2023-06-21T19:28:06.603319Z",
    "updatedOn": "2023-06-21T21:14:22.093957Z",
    "isSeason": false,
    "isTopLevelSeason": false,
    "isPartialSeason": false,
    "isEventInSeason": false
}`

Event Instance:
`{
  "id": 2493803,
  "key": "9feb7ccc-07ba-4bde-b4c0-e045706165e5",
  "tableBookingConfig": {
    "mode": "INHERIT"
  },
  "forSaleConfig": null,
  "chartKey": "2211787c-7d02-614f-6399-1ed6e5afb4a3",
  "createdOn": "2023-06-21T19:28:06.603Z",
  "updatedOn": "2023-06-21T21:14:22.093Z",
  "channels": null,
  "isTopLevelSeason": false,
  "isPartialSeason": false,
  "isEventInSeason": false,
  "categories": null
}`

**Comment by mroloux** [comment]
Hi, [v76.2.0](https://github.com/seatsio/seatsio-js/releases/tag/v76.2.0) now supports name (and date).

Thanks for reporting this!
