### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by deinok** [seatsio/seatsio-js#33]
Hi, we would like to know if Seats.io would accept TypeScript support related PRs

**Comment by mroloux** [comment]
Would that mean changes to the seatsio-js repository? Or a brand new repository (e.g. seatsio-typescript)?

**Comment by deinok** [comment]
Changes to the repo. But that changes are not going to create any breaking-changes.

That would allow clients to have type definitions automatically if they use TypeScript. And in the process it will probably detect a lot of possible bugs.

**Comment by mroloux** [comment]
Sure, sounds good. Thanks!
