### ISSUE TITLE
Bump Axios Dependency to Fix Vulnerability (GHSA-8hc4-vh64-cxmj)

### ISSUE THREAD

**Issue by alexpechkarev** [seatsio/seatsio-js#344]
The Seats.io JS SDK is currently using an older version of the axios library (1.3.2 - 1.7.3), which is affected by a high-severity Server-Side Request Forgery vulnerability (GHSA-8hc4-vh64-cxmj). 

To mitigate this security risk, please bump the `axios` dependency to version 1.7.5?

**Comment by mroloux** [comment]
Thanks, that's fixed in https://github.com/seatsio/seatsio-js/releases/tag/v81.17.0
