### ISSUE TITLE
Entry point is no longer published since v81.18.0

### ISSUE THREAD

**Issue by ooflorent** [seatsio/seatsio-js#350]
Since v81.18.0, `dist/src/index.js` and `dist/src/index.d.ts` are no longer included in the published package on npm.

Because of this, the following statement fails:
```ts
import { HoldToken, Region, SeatsioClient } from "seatsio";
//                                               ^^^^^^^^^
//            Cannot find module 'seatsio' or its corresponding type declarations
```

**Comment by mroloux** [comment]
Hi, thanks for reporting this! There was an issue with our build. Should be fine in v81.20.0 though.
