### ISSUE TITLE
How to import Region

### ISSUE THREAD

**Issue by hos** [seatsio/seatsio-js#68]
In your `README` you are using `Region.EU()` but there is no example how to import it. I found that it's not exported in [index.js](https://github.com/seatsio/seatsio-js/blob/master/index.js). Is the right way of doing it using `require('seatsio/src/Region')`?

**Comment by mroloux** [comment]
Hi,

Good catch: that was an oversight from our end. In the latest release (v63.1.0), you can now import Region via

```
import { SeatsioClient, Region } from 'seatsio'
```
