### ISSUE TITLE
How to see breaking changes between major versions?

### ISSUE THREAD

**Issue by coatesap** [seatsio/seatsio-js#96]
Hi, is there any documentation about what breaking changes are in each major version release?

eg. I'd like to know what we would need to look out for if we were upgrading from v62 to v63...

**Comment by bverbeken** [comment]
Hi, 

The [releases page](https://github.com/seatsio/seatsio-js/releases) shows what changed in each release. As you'll see, we tend to create very small, single-change releases. 

Specifically for v63, you'll see that that version added exponential backoff in case of 429 - Too Many Requests errors from server. This would not break backwards compatibility in the majority of cases, but it _could_, theoretically. Hence the major version bump. In short: you should be fine ;)

**Comment by coatesap** [comment]
Thanks @bverbeken - it was the releases page I was looking at, but I couldn't see how exponential backoff was a breaking change, so I was worried there were other changes in that release that weren't listed.
